name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5  # 병렬 실행 수 설정

    steps:
    # 1. 리포지토리 코드 체크아웃
    - uses: actions/checkout@v4

    # 2. Python 3.10 설치
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    # 3. Conda 설치 및 경로 추가
    - name: Add conda to system path
      run: |
        echo "$HOME/miniconda/bin" >> $GITHUB_PATH
        curl -fsSL https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        source "$HOME/miniconda/etc/profile.d/conda.sh"
        conda init bash
        conda update -y conda  # conda 최신 버전으로 업데이트

    # 4. Conda solver를 classic으로 변경
    - name: Set conda solver to classic
      run: |
        conda config --set solver classic  # classic solver 사용 설정

    # 5. 의존성 설치
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base  # environment.yml을 사용해 의존성 설치

    # 6. Lint with flake8
    - name: Install and run flake8
      run: |
        conda install flake8  # flake8 설치
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics  # 코드에서 오류 찾기
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics  # 경고를 오류로 처리하지 않음

    # 7. Test with pytest
    - name: Install and run pytest
      run: |
        conda install pytest  # pytest 설치
        pytest  # 테스트 실행
